version: "3"

services:
  docker-gateway:
    image: markwylde/docker-gateway
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../acme-generator/certs:/certs
    environment:
      SSL_KEY_PATH: /certs/privkey.pem
      SSL_CERT_PATH: /certs/chain.pem

  example:
    image: example
    deploy:
      labels:
        docker-gateway.0: https://hello.test
