version: "3"

services:
  docker-gateway:
    image: markwylde/docker-gateway
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      SSL_KEY_PATH: /etc/letsencrypt/live/example.com/privkey.pem
      SSL_CERT_PATH: /etc/letsencrypt/live/example.com/cert.pem
      SSL_CHAIN_PATH: /etc/letsencrypt/live/example.com/fullchain.pem
    networks:
      - web

networks:
  web:
    external: true
