version: "3"

services:
  readonly-docker:
    image: tecnativa/docker-socket-proxy
    privileged: true
    environment:
      CONTAINERS: 1
      SERVICES: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  docker-gateway:
    image: local/docker-gateway
    ports:
      - 80:80
      - 443:443
    environment:
      DOCKER_URL: http://readonly-docker:2375
    volumes:
      - ./certs:/certs:ro

  example-one:
    image: local/example
    deploy:
      labels:
        docker-gateway.0: https://one.test/(.*) -> https://example-one:8080/$$1

  example-two:
    image: local/example
    deploy:
      labels:
        docker-gateway.0: https://two.test/(.*) -> https://example-two:8080/$$1

  example-three:
    image: local/example
    deploy:
      labels:
        docker-gateway.0: https://something.three.test/(.*) -> https://example-three:8080/$$1
