version: "3"

services:
  docker-gateway:
    image: local/docker-gateway
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./example/certs:/certs
    environment:
      SSL_KEY_PATH: /certs/localhost.privkey.pem
      SSL_CERT_PATH: /certs/localhost.cert.pem

  example:
    image: local/example
    deploy:
      labels:
        docker-gateway.0: https://hello.test -> 8080
