version: "3"

services:
  docker-gateway:
    image: local/docker-gateway
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/certs

  example-one:
    image: local/example
    deploy:
      labels:
        docker-gateway.0: https://one.test -> https://example-one:8080

  example-two:
    image: local/example
    deploy:
      labels:
        docker-gateway.0: https://two.test -> https://example-two:8080

  example-three:
    image: local/example
    deploy:
      labels:
        docker-gateway.0: https://something.three.test -> https://example-three:8080
