version: "3"

services:
  spy:
    image: spy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - web

networks:
  web:
    external: true
