version: "3"

services:
  # docker-gateway:
  #   build:
  #     context: .
  #   ports:
  #     - 80:80
  #     - 443:443
  #     - 8080:8080
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./certs:/certs:ro

  example-one:
    build:
      context: ./example
    labels:
      docker-gateway.0: https://one.test/(.*) -> http://example-one:8080/$$1

  example-two:
    build:
      context: ./example
    labels:
      docker-gateway.0: https://two.test/(.*) -> http://example-two:8080/$$1

  example-three:
    build:
      context: ./example
    labels:
      docker-gateway.0: https://something.three.test/(.*) -> http://example-three:8080/$$1
